### ISSUE TITLE
general issues

### ISSUE THREAD

**Issue by igorTT** [BelohvostovAlex/gulp#1]
Надопривести в порядок отступы- должно быть два пробела везде
Используй только стрелочные функции. Объявление функции через 'function'- только в тех местах, где необходима работа с контекстом вызова.
Добавь в package.json команды, которые запускают gulp (serve)
В названия классов не используй camelCase
БЭМ- это блок__элемент--модификация. Перепиши все блок__элемент__элемент__элемент, если хочешь использовать бэм.
Прими для себя правило в css использовать вложенность не более двух.
```css
.class-name {
  & .next-class-name {
    color: red;
  }
}
```
Приведи в порядок семантику. Касается заголовков.
Все картинки в png. Замени на необходимые форматы.
https://www.figma.com/file/ShL4U22HRytQWtlFVwnpIc/Game-Landing?node-id=83%3A4
Давай вот эту секцию добавим.

**Comment by BelohvostovAlex** [comment]
В scss старался везде делать вложенность не больше двух, в нек. случаях не хотелось отделять before/after, оставил - получилось очень редко нестинг - 3.
Картинки поменял, где не нужен png + не знаю норм или нет, в gulp добавил task для конвертации всех картинок в webp формат, получились меньше по размерам, если не одобряешь - удалю.
Немного поменял дерево проекта, показалось более удобно, чем пример у Минина.
Секцию добавил, остальное вроде тоже подкорректил

**Comment by igorTT** [comment]
webp- отлично.
Дальше будем работать работать через issue- pull request
